import { useState, type FormEvent } from 'react'
import type { ResearchMilestone, ResearchProject } from '../../types/domain'
import { ProjectForm } from './ProjectForm'

type MilestoneInput = Omit<ResearchMilestone, 'id' | 'createdAt' | 'updatedAt'>

export function ProjectOverview({ project, milestones, onProjectUpdate, onMilestoneCreate, onMilestoneUpdate, onMilestoneDelete }: { project: ResearchProject; milestones: ResearchMilestone[]; onProjectUpdate(changes: Partial<ResearchProject>): Promise<unknown>; onMilestoneCreate(input: MilestoneInput): Promise<unknown>; onMilestoneUpdate(id: string, changes: Partial<ResearchMilestone>): Promise<unknown>; onMilestoneDelete(id: string): Promise<unknown> }) {
  const [title, setTitle] = useState(''); const [date, setDate] = useState(''); const [priority, setPriority] = useState<ResearchMilestone['priority']>('medium')
  async function create(event: FormEvent) { event.preventDefault(); await onMilestoneCreate({ projectId: project.id, title, date, priority, status: 'pending' }); setTitle(''); setDate('') }
  return <div className="research-tab-content"><article className="panel"><div className="panel__heading"><div><span className="eyebrow">PROJECT</span><h2>项目资料</h2></div><button className="danger-button" disabled={project.status === 'archived'} onClick={() => void onProjectUpdate({ status: 'archived' })} type="button">{project.status === 'archived' ? '已归档' : '归档项目'}</button></div><ProjectForm initial={project} key={project.updatedAt} onSubmit={(input) => onProjectUpdate(input)} /></article><article className="panel"><div className="panel__heading"><div><span className="eyebrow">MILESTONES</span><h2>里程碑</h2></div></div><form className="inline-create" onSubmit={create}><input aria-label="里程碑标题" onChange={(e) => setTitle(e.target.value)} placeholder="里程碑标题" required value={title} /><input aria-label="里程碑日期" onChange={(e) => setDate(e.target.value)} required type="date" value={date} /><select aria-label="里程碑优先级" onChange={(e) => setPriority(e.target.value as ResearchMilestone['priority'])} value={priority}><option value="high">高</option><option value="medium">中</option><option value="low">低</option></select><button className="primary-button" type="submit">添加里程碑</button></form><ul className="record-list">{milestones.map((item) => <li key={item.id}><input aria-label={`完成里程碑：${item.title}`} checked={item.status === 'completed'} onChange={() => void onMilestoneUpdate(item.id, { status: item.status === 'completed' ? 'pending' : 'completed' })} type="checkbox" /><span><input aria-label={`编辑里程碑标题：${item.title}`} defaultValue={item.title} onBlur={(e) => void onMilestoneUpdate(item.id, { title: e.target.value })} /><input aria-label={`编辑里程碑日期：${item.title}`} defaultValue={item.date} onBlur={(e) => void onMilestoneUpdate(item.id, { date: e.target.value })} type="date" /></span><button className="text-danger" onClick={() => void onMilestoneDelete(item.id)} type="button">删除</button></li>)}</ul></article></div>
}
