import { Plus, Trash2 } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import type { FitnessExercise, FitnessPlan } from '../../types/domain'

type Draft = Omit<FitnessExercise, 'id'|'createdAt'|'updatedAt'|'planId'|'order'>
type PlanInput = Omit<FitnessPlan, 'id'|'createdAt'|'updatedAt'>
const emptyDraft = (): Draft => ({ name: '', sets: 3, reps: 10 })

export function WorkoutForm({ date, onSubmit }: { date: string; onSubmit(plan: PlanInput, exercises: Draft[]): Promise<unknown> }) {
  const [title, setTitle] = useState(''); const [time, setTime] = useState(''); const [exercises, setExercises] = useState<Draft[]>([emptyDraft()]); const [error, setError] = useState('')
  function update(index: number, changes: Partial<Draft>) { setExercises((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, ...changes } : item)) }
  async function submit(event: FormEvent) { event.preventDefault(); try { await onSubmit({ title, date, time: time || undefined, status: 'pending', priority: 'medium' }, exercises); setTitle(''); setTime(''); setExercises([emptyDraft()]); setError('') } catch (caught) { setError(caught instanceof Error ? caught.message : '保存失败') } }
  return <form className="workout-form" onSubmit={submit}><div className="inline-create"><input aria-label="训练标题" onChange={(e) => setTitle(e.target.value)} placeholder="例如：上肢训练" required value={title} /><input aria-label="训练时间" onChange={(e) => setTime(e.target.value)} type="time" value={time} /></div><fieldset><legend>训练动作</legend>{exercises.map((item, index) => <div className="exercise-row" key={index}><input aria-label={`动作 ${index + 1} 名称`} onChange={(e) => update(index, { name: e.target.value })} placeholder="动作名称" required value={item.name} /><label>组<input aria-label={`动作 ${index + 1} 组数`} min="1" onChange={(e) => update(index, { sets: Number(e.target.value) })} type="number" value={item.sets} /></label><label>次<input aria-label={`动作 ${index + 1} 次数`} min="1" onChange={(e) => update(index, { reps: Number(e.target.value) })} type="number" value={item.reps ?? ''} /></label><label>分钟<input aria-label={`动作 ${index + 1} 时长`} min="0" onChange={(e) => update(index, { durationMinutes: e.target.value ? Number(e.target.value) : undefined })} type="number" value={item.durationMinutes ?? ''} /></label><label>kg<input aria-label={`动作 ${index + 1} 重量`} min="0" onChange={(e) => update(index, { weightKg: e.target.value ? Number(e.target.value) : undefined })} type="number" value={item.weightKg ?? ''} /></label><input aria-label={`动作 ${index + 1} 备注`} onChange={(e) => update(index, { note: e.target.value || undefined })} placeholder="动作备注" value={item.note ?? ''} /><button aria-label={`删除动作 ${index + 1}`} className="icon-button icon-button--danger" disabled={exercises.length === 1} onClick={() => setExercises((items) => items.filter((_, itemIndex) => itemIndex !== index))} type="button"><Trash2 aria-hidden="true" size={16} /></button></div>)}</fieldset><div className="form-actions"><button className="text-button" onClick={() => setExercises((items) => [...items, emptyDraft()])} type="button"><Plus aria-hidden="true" size={16} />添加动作</button><button className="primary-button" type="submit">保存训练</button></div>{error ? <p className="form-error">{error}</p> : null}</form>
}
