import { expect, test } from '@playwright/test'

test('fitness plan stores ordered exercises, copies, and appears in today', async ({ page }) => {
  await page.goto('/#/fitness/2026-09-03')
  await page.getByLabel('训练标题').fill('上肢训练')
  await page.getByLabel('动作 1 名称').fill('卧推')
  await page.getByLabel('动作 1 备注').fill('控制离心阶段')
  await page.getByRole('button', { name: '添加动作' }).click()
  await page.getByLabel('动作 2 名称').fill('划船')
  await page.getByRole('button', { name: '保存训练' }).click()
  await expect(page.getByText('上肢训练')).toBeVisible()
  await expect(page.locator('.workout-card ol').getByText('卧推')).toBeVisible()
  await page.getByText('编辑训练').click()
  await page.getByLabel('编辑训练标题：上肢训练').fill('上肢力量训练')
  await page.getByLabel('编辑训练标题：上肢训练').blur()
  await page.getByLabel('编辑动作名称：卧推').fill('杠铃卧推')
  await page.getByLabel('编辑动作名称：卧推').blur()
  await page.getByLabel('添加训练动作：上肢力量训练').click()
  await page.getByLabel('编辑动作名称：新动作').fill('肩推')
  await page.getByLabel('编辑动作名称：新动作').blur()
  await expect(page.locator('.workout-card ol').getByText('肩推')).toBeVisible()
  await page.getByLabel('上移：划船').click()
  await expect(page.locator('.workout-card li').first()).toContainText('划船')

  await page.getByLabel('复制训练：上肢力量训练').click()
  await page.getByRole('link', { name: '今日计划' }).click()
  await expect(page).toHaveURL(/#\/today$/)
  await page.getByLabel('选择日期').fill('2026-09-03')
  await expect(page).toHaveURL(/#\/today\/2026-09-03$/)
  await expect(page.getByText('训练：上肢力量训练')).toBeVisible()
})
