Add-Type -AssemblyName System.Drawing
$iconBitmap = New-Object System.Drawing.Bitmap(256, 256)
$iconGraphics = [System.Drawing.Graphics]::FromImage($iconBitmap)
$iconGraphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
$iconGraphics.Clear([System.Drawing.Color]::FromArgb(15, 23, 42))
$iconBrush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(13, 148, 136))
$iconGraphics.FillEllipse($iconBrush, 24, 24, 208, 208)
$iconPen = New-Object System.Drawing.Pen([System.Drawing.Color]::White, 18)
$iconGraphics.DrawLine($iconPen, 128, 72, 128, 184)
$iconGraphics.DrawLine($iconPen, 72, 128, 184, 128)
$iconStream = New-Object System.IO.MemoryStream
$iconBitmap.Save($iconStream, [System.Drawing.Imaging.ImageFormat]::Png)
$iconBytes = $iconStream.ToArray()
$iconOutput = [System.IO.File]::Create((Join-Path $PSScriptRoot '..\desktop\icon.ico'))
$iconWriter = New-Object System.IO.BinaryWriter($iconOutput)
$iconWriter.Write([uint16]0)
$iconWriter.Write([uint16]1)
$iconWriter.Write([uint16]1)
$iconWriter.Write([byte]0)
$iconWriter.Write([byte]0)
$iconWriter.Write([byte]0)
$iconWriter.Write([byte]0)
$iconWriter.Write([uint16]1)
$iconWriter.Write([uint16]32)
$iconWriter.Write([uint32]$iconBytes.Length)
$iconWriter.Write([uint32]22)
$iconWriter.Write($iconBytes)
$iconWriter.Dispose()
$iconStream.Dispose()
$iconPen.Dispose()
$iconBrush.Dispose()
$iconGraphics.Dispose()
$iconBitmap.Dispose()
